// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2IuDL4VKGKCT3y2cK4zfMVguLfjyzYfs',
    appId: '1:913505709508:web:d4a8fb5e73eb8ea5214891',
    messagingSenderId: '913505709508',
    projectId: 'fir-storage-78037',
    authDomain: 'fir-storage-78037.firebaseapp.com',
    storageBucket: 'fir-storage-78037.firebasestorage.app',
    measurementId: 'G-Z3PNWPNZNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfL06fyy1wrALc9zxH1uv0pu11neFeZ6g',
    appId: '1:913505709508:android:8b9b2ecf9dc3ad58214891',
    messagingSenderId: '913505709508',
    projectId: 'fir-storage-78037',
    storageBucket: 'fir-storage-78037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa9HUKhOnsMwECtiNyTzrXhMKkpiAGuk4',
    appId: '1:913505709508:ios:6013fd28bf20a9a6214891',
    messagingSenderId: '913505709508',
    projectId: 'fir-storage-78037',
    storageBucket: 'fir-storage-78037.firebasestorage.app',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );

}